repos:

  - repo: local
    hooks:
      - id: rome
        name: Rome
        entry: npx
        args: [rome, "format", ".", "--write"]
        language: system
        stages: [commit]

      -   id: eslint
          name: eslint
          description: ''
          entry: eslint
          language: node
          'types': [javascript]
          args: []
          require_serial: false
          additional_dependencies: ["eslint@8.57.0"]
          minimum_pre_commit_version: '0'
          stages: [commit]

      - id: run-tests
        name: Run Tests
        entry: npm
        args: [run, test]
        language: system
        pass_filenames: false
        stages: [commit]

      - id: build
        name: Build
        entry: npx
        args: [next, build]
        language: system
        pass_filenames: false
        stages: [push]
